import {defineArrayMember, defineField, defineType} from 'sanity';

export const siteSettings = defineType({
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    {name: 'brand', title: 'Brand', default: true},
    {name: 'seo', title: 'SEO'},
    {name: 'links', title: 'Links'},
    {name: 'contact', title: 'Contact'},
  ],
  fields: [
    defineField({
      name: 'siteName',
      title: 'Site Name',
      type: 'string',
      group: 'brand',
      description: 'Public website name used in global UI and metadata defaults.',
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: 'podcastName',
      title: 'Podcast Name',
      type: 'string',
      group: 'brand',
      description: 'Official podcast name shown in editorial copy and platform references.',
      validation: (rule) => rule.required().max(120),
    }),
    defineField({
      name: 'positioningStatement',
      title: 'Global Positioning Statement',
      type: 'text',
      rows: 3,
      group: 'brand',
      description: 'One concise sentence describing the show mission and audience.',
      validation: (rule) => rule.required().max(220),
    }),
    defineField({
      name: 'logo',
      title: 'Logo',
      type: 'imageWithAlt',
      group: 'brand',
      description: 'Primary brand logo image for future header/footer usage.',
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon / Source Icon',
      type: 'file',
      group: 'brand',
      description: 'Upload the source icon file for favicon generation (for example .svg, .png, or .ico).',
      options: {
        accept: '.svg,.png,.ico',
      },
    }),
    defineField({
      name: 'defaultSeoTitle',
      title: 'Default SEO Title',
      type: 'string',
      group: 'seo',
      description: 'Fallback title used when a page does not define a custom SEO title.',
      validation: (rule) => rule.required().max(70),
    }),
    defineField({
      name: 'defaultSeoDescription',
      title: 'Default SEO Description',
      type: 'text',
      rows: 3,
      group: 'seo',
      description: 'Fallback meta description used for general pages without a custom description.',
      validation: (rule) => rule.required().max(180),
    }),
    defineField({
      name: 'defaultOgImage',
      title: 'Default OG Image',
      type: 'imageWithAlt',
      group: 'seo',
      description: 'Fallback social share image used when a page-specific OG image is not set.',
    }),
    defineField({
      name: 'podcastPlatformLinks',
      title: 'Podcast Platform Links',
      type: 'array',
      group: 'links',
      description: 'Links to the show homepage on podcast platforms (for example Apple Podcasts or Spotify show page).',
      of: [defineArrayMember({type: 'externalLink'})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'riversideRssUrl',
      title: 'Riverside RSS URL',
      type: 'url',
      group: 'links',
      description: 'Canonical Riverside podcast RSS feed URL. Keep this current for future sync work.',
      validation: (rule) => rule.uri({allowRelative: false, scheme: ['http', 'https']}),
    }),
    defineField({
      name: 'socialLinks',
      title: 'Social Links',
      type: 'array',
      group: 'links',
      description: 'Public social profile links for Colorado Tech People.',
      of: [defineArrayMember({type: 'externalLink'})],
      validation: (rule) => rule.unique(),
    }),
    defineField({
      name: 'contactEmailDisplay',
      title: 'Contact / Manager Email (Display Text)',
      type: 'string',
      group: 'contact',
      description: 'Display text for a contact email shown in public copy (for example hello@domain.com).',
      validation: (rule) => rule.email().max(120),
    }),
  ],
  preview: {
    select: {
      title: 'siteName',
      subtitle: 'podcastName',
      media: 'logo',
    },
    prepare(selection) {
      return {
        title: selection.title || 'Site Settings',
        subtitle: selection.subtitle || 'Global podcast and site configuration',
        media: selection.media,
      };
    },
  },
});
